name: Build and push Docker image

on:
  push:
    branches:
      - master
      - azure-container-reg

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login ${REGISTRY_URL} -u ${{ secrets.ACR_USERNAME }} --password-stdin


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./VechileService/Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/vehicleservice:latest
            ${{ secrets.REGISTRY_URL }}/vehicleservice:${{ github.sha }}
