name: Lint and Test Node App

on:
  push:
    branches:
      - "*"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd VehicleService/src
          npm install

      - name: Run linting and tests
        run: |
          cd VehicleService/src
          npm run lint
          npm run test
